#:schema node_modules/wrangler/config-schema.json
name = "smail"
compatibility_date = "2024-09-25"
main = "app/worker.ts"
assets = { directory = "./build/client" }

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "ec9c613d958c42809d5d9fa8d7daf879"

[[d1_databases]]
binding = "DB"
database_name = "smail"
database_id = "082acd17-aa57-4f40-8dee-cf8196214f3b"
preview_database_id = "082acd17-aa57-4f40-8dee-cf8196214f3b"
migrations_dir = "app/drizzle"
