#:schema node_modules/wrangler/config-schema.json
name = "smail"
compatibility_date = "2024-09-25"
main = "app/worker.ts"
assets = { directory = "./build/client" }

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "80d4e1f23646433f8c331809c0ed6ac7"

[[d1_databases]]
binding = "DB"
database_name = "wx_email"
database_id = "46cb6e1a-5c24-44e7-ba39-be66b81138a8"
preview_database_id = "46cb6e1a-5c24-44e7-ba39-be66b81138a8"
migrations_dir = "app/drizzle"
